version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bootcamp-node-app:latest
    container_name: bootcamp-node-app
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./images:/usr/app/images:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app-data:

networks:
  app-network:
    driver: bridge
